quarkus.http.port=8081
 
# ─────────────────────────────────────────────
# OIDC Client nomeado: manager (obtém o token)
# ─────────────────────────────────────────────
quarkus.oidc-client.manager.auth-server-url=http://localhost:8180/realms/teste
quarkus.oidc-client.manager.client-id=meu-client
quarkus.oidc-client.manager.credentials.secret=Fk71DINa3ZwNH272cAvU3Hz1jao5vS8r
quarkus.oidc-client.manager.grant.type=client
quarkus.oidc-client.manager.scopes=openid
 
# ─────────────────────────────────────────────
# REST Client: API corporativa (consome o token)
# ─────────────────────────────────────────────
quarkus.rest-client.corporativo.url=http://api-corporativa:8080
quarkus.rest-client.corporativo.scope=jakarta.inject.Singleton


quarkus.datasource.db-kind=h2
#quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/testdb
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.database.generation=update

