quarkus.http.port=8081

# REST Client - API Manager keycloak
quarkus.rest-client.apimanager.url=http://localhost:8180
quarkus.rest-client.apimanager.scope=jakarta.inject.Singleton
app.auth.keycloak.grant-type=client_credentials
app.auth.keycloak.client-id=meu-client
app.auth.keycloak.client-secret=6eIzgGC1kVUYXqQxAixdzvf96CzW0ht4
app.auth.keycloak.scope=openid