quarkus.http.port=8081

# OIDC Client - Keycloak (client_credentials)
quarkus.oidc-client.auth-server-url=http://localhost:8180/realms/teste
quarkus.oidc-client.client-id=meu-client
quarkus.oidc-client.credentials.secret=Fk71DINa3ZwNH272cAvU3Hz1jao5vS8r
quarkus.oidc-client.grant.type=client
quarkus.oidc-client.scopes=openid

